#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWNC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYBANVE")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHITIETCHUYEN(CHITIETCHUYEN instance);
    partial void UpdateCHITIETCHUYEN(CHITIETCHUYEN instance);
    partial void DeleteCHITIETCHUYEN(CHITIETCHUYEN instance);
    partial void InsertXE(XE instance);
    partial void UpdateXE(XE instance);
    partial void DeleteXE(XE instance);
    partial void InsertCHONGOI(CHONGOI instance);
    partial void UpdateCHONGOI(CHONGOI instance);
    partial void DeleteCHONGOI(CHONGOI instance);
    partial void InsertKHACH(KHACH instance);
    partial void UpdateKHACH(KHACH instance);
    partial void DeleteKHACH(KHACH instance);
    partial void InsertMANHINH(MANHINH instance);
    partial void UpdateMANHINH(MANHINH instance);
    partial void DeleteMANHINH(MANHINH instance);
    partial void InsertNDNHOMND(NDNHOMND instance);
    partial void UpdateNDNHOMND(NDNHOMND instance);
    partial void DeleteNDNHOMND(NDNHOMND instance);
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertNHOMNGUOIDUNG(NHOMNGUOIDUNG instance);
    partial void UpdateNHOMNGUOIDUNG(NHOMNGUOIDUNG instance);
    partial void DeleteNHOMNGUOIDUNG(NHOMNGUOIDUNG instance);
    partial void InsertPHANQUYEN(PHANQUYEN instance);
    partial void UpdatePHANQUYEN(PHANQUYEN instance);
    partial void DeletePHANQUYEN(PHANQUYEN instance);
    partial void InsertTAIXE(TAIXE instance);
    partial void UpdateTAIXE(TAIXE instance);
    partial void DeleteTAIXE(TAIXE instance);
    partial void InsertTUYEN(TUYEN instance);
    partial void UpdateTUYEN(TUYEN instance);
    partial void DeleteTUYEN(TUYEN instance);
    partial void InsertVE(VE instance);
    partial void UpdateVE(VE instance);
    partial void DeleteVE(VE instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DoAn_LTWNC.Properties.Settings.Default.QUANLYBANVEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHITIETCHUYEN> CHITIETCHUYENs
		{
			get
			{
				return this.GetTable<CHITIETCHUYEN>();
			}
		}
		
		public System.Data.Linq.Table<XE> XEs
		{
			get
			{
				return this.GetTable<XE>();
			}
		}
		
		public System.Data.Linq.Table<CHONGOI> CHONGOIs
		{
			get
			{
				return this.GetTable<CHONGOI>();
			}
		}
		
		public System.Data.Linq.Table<KHACH> KHACHes
		{
			get
			{
				return this.GetTable<KHACH>();
			}
		}
		
		public System.Data.Linq.Table<MANHINH> MANHINHs
		{
			get
			{
				return this.GetTable<MANHINH>();
			}
		}
		
		public System.Data.Linq.Table<NDNHOMND> NDNHOMNDs
		{
			get
			{
				return this.GetTable<NDNHOMND>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<NHOMNGUOIDUNG> NHOMNGUOIDUNGs
		{
			get
			{
				return this.GetTable<NHOMNGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this.GetTable<PHANQUYEN>();
			}
		}
		
		public System.Data.Linq.Table<TAIXE> TAIXEs
		{
			get
			{
				return this.GetTable<TAIXE>();
			}
		}
		
		public System.Data.Linq.Table<TUYEN> TUYENs
		{
			get
			{
				return this.GetTable<TUYEN>();
			}
		}
		
		public System.Data.Linq.Table<VE> VEs
		{
			get
			{
				return this.GetTable<VE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETCHUYEN")]
	public partial class CHITIETCHUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACHUYEN;
		
		private string _MATUYEN;
		
		private string _MAXE;
		
		private string _MATAIXE;
		
		private System.TimeSpan _GIOCHAY;
		
		private System.DateTime _NGAYCHAY;
		
		private int _THOIGIANCHAY;
		
		private string _DIEMDON;
		
		private string _DIEMTRA;
		
		private double _GIA;
		
		private EntityRef<XE> _XE;
		
		private EntityRef<TAIXE> _TAIXE;
		
		private EntityRef<TUYEN> _TUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHUYENChanging(string value);
    partial void OnMACHUYENChanged();
    partial void OnMATUYENChanging(string value);
    partial void OnMATUYENChanged();
    partial void OnMAXEChanging(string value);
    partial void OnMAXEChanged();
    partial void OnMATAIXEChanging(string value);
    partial void OnMATAIXEChanged();
    partial void OnGIOCHAYChanging(System.TimeSpan value);
    partial void OnGIOCHAYChanged();
    partial void OnNGAYCHAYChanging(System.DateTime value);
    partial void OnNGAYCHAYChanged();
    partial void OnTHOIGIANCHAYChanging(int value);
    partial void OnTHOIGIANCHAYChanged();
    partial void OnDIEMDONChanging(string value);
    partial void OnDIEMDONChanged();
    partial void OnDIEMTRAChanging(string value);
    partial void OnDIEMTRAChanged();
    partial void OnGIAChanging(double value);
    partial void OnGIAChanged();
    #endregion
		
		public CHITIETCHUYEN()
		{
			this._XE = default(EntityRef<XE>);
			this._TAIXE = default(EntityRef<TAIXE>);
			this._TUYEN = default(EntityRef<TUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUYEN", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACHUYEN
		{
			get
			{
				return this._MACHUYEN;
			}
			set
			{
				if ((this._MACHUYEN != value))
				{
					this.OnMACHUYENChanging(value);
					this.SendPropertyChanging();
					this._MACHUYEN = value;
					this.SendPropertyChanged("MACHUYEN");
					this.OnMACHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATUYEN", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MATUYEN
		{
			get
			{
				return this._MATUYEN;
			}
			set
			{
				if ((this._MATUYEN != value))
				{
					if (this._TUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATUYENChanging(value);
					this.SendPropertyChanging();
					this._MATUYEN = value;
					this.SendPropertyChanged("MATUYEN");
					this.OnMATUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXE", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MAXE
		{
			get
			{
				return this._MAXE;
			}
			set
			{
				if ((this._MAXE != value))
				{
					if (this._XE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAXEChanging(value);
					this.SendPropertyChanging();
					this._MAXE = value;
					this.SendPropertyChanged("MAXE");
					this.OnMAXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATAIXE", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MATAIXE
		{
			get
			{
				return this._MATAIXE;
			}
			set
			{
				if ((this._MATAIXE != value))
				{
					if (this._TAIXE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATAIXEChanging(value);
					this.SendPropertyChanging();
					this._MATAIXE = value;
					this.SendPropertyChanged("MATAIXE");
					this.OnMATAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOCHAY", DbType="Time NOT NULL")]
		public System.TimeSpan GIOCHAY
		{
			get
			{
				return this._GIOCHAY;
			}
			set
			{
				if ((this._GIOCHAY != value))
				{
					this.OnGIOCHAYChanging(value);
					this.SendPropertyChanging();
					this._GIOCHAY = value;
					this.SendPropertyChanged("GIOCHAY");
					this.OnGIOCHAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCHAY", DbType="Date NOT NULL")]
		public System.DateTime NGAYCHAY
		{
			get
			{
				return this._NGAYCHAY;
			}
			set
			{
				if ((this._NGAYCHAY != value))
				{
					this.OnNGAYCHAYChanging(value);
					this.SendPropertyChanging();
					this._NGAYCHAY = value;
					this.SendPropertyChanged("NGAYCHAY");
					this.OnNGAYCHAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANCHAY", DbType="Int NOT NULL")]
		public int THOIGIANCHAY
		{
			get
			{
				return this._THOIGIANCHAY;
			}
			set
			{
				if ((this._THOIGIANCHAY != value))
				{
					this.OnTHOIGIANCHAYChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANCHAY = value;
					this.SendPropertyChanged("THOIGIANCHAY");
					this.OnTHOIGIANCHAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMDON", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIEMDON
		{
			get
			{
				return this._DIEMDON;
			}
			set
			{
				if ((this._DIEMDON != value))
				{
					this.OnDIEMDONChanging(value);
					this.SendPropertyChanging();
					this._DIEMDON = value;
					this.SendPropertyChanged("DIEMDON");
					this.OnDIEMDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMTRA", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIEMTRA
		{
			get
			{
				return this._DIEMTRA;
			}
			set
			{
				if ((this._DIEMTRA != value))
				{
					this.OnDIEMTRAChanging(value);
					this.SendPropertyChanging();
					this._DIEMTRA = value;
					this.SendPropertyChanged("DIEMTRA");
					this.OnDIEMTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="Float NOT NULL")]
		public double GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XE_CHITIETCHUYEN", Storage="_XE", ThisKey="MAXE", OtherKey="MAXE", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public XE XE
		{
			get
			{
				return this._XE.Entity;
			}
			set
			{
				XE previousValue = this._XE.Entity;
				if (((previousValue != value) 
							|| (this._XE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XE.Entity = null;
						previousValue.CHITIETCHUYENs.Remove(this);
					}
					this._XE.Entity = value;
					if ((value != null))
					{
						value.CHITIETCHUYENs.Add(this);
						this._MAXE = value.MAXE;
					}
					else
					{
						this._MAXE = default(string);
					}
					this.SendPropertyChanged("XE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIXE_CHITIETCHUYEN", Storage="_TAIXE", ThisKey="MATAIXE", OtherKey="MATAIXE", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TAIXE TAIXE
		{
			get
			{
				return this._TAIXE.Entity;
			}
			set
			{
				TAIXE previousValue = this._TAIXE.Entity;
				if (((previousValue != value) 
							|| (this._TAIXE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIXE.Entity = null;
						previousValue.CHITIETCHUYENs.Remove(this);
					}
					this._TAIXE.Entity = value;
					if ((value != null))
					{
						value.CHITIETCHUYENs.Add(this);
						this._MATAIXE = value.MATAIXE;
					}
					else
					{
						this._MATAIXE = default(string);
					}
					this.SendPropertyChanged("TAIXE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUYEN_CHITIETCHUYEN", Storage="_TUYEN", ThisKey="MATUYEN", OtherKey="MATUYEN", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TUYEN TUYEN
		{
			get
			{
				return this._TUYEN.Entity;
			}
			set
			{
				TUYEN previousValue = this._TUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TUYEN.Entity = null;
						previousValue.CHITIETCHUYENs.Remove(this);
					}
					this._TUYEN.Entity = value;
					if ((value != null))
					{
						value.CHITIETCHUYENs.Add(this);
						this._MATUYEN = value.MATUYEN;
					}
					else
					{
						this._MATUYEN = default(string);
					}
					this.SendPropertyChanged("TUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.XE")]
	public partial class XE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAXE;
		
		private string _TENXE;
		
		private string _SODT;
		
		private int _SOCHO;
		
		private EntitySet<CHITIETCHUYEN> _CHITIETCHUYENs;
		
		private EntitySet<CHONGOI> _CHONGOIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAXEChanging(string value);
    partial void OnMAXEChanged();
    partial void OnTENXEChanging(string value);
    partial void OnTENXEChanged();
    partial void OnSODTChanging(string value);
    partial void OnSODTChanged();
    partial void OnSOCHOChanging(int value);
    partial void OnSOCHOChanged();
    #endregion
		
		public XE()
		{
			this._CHITIETCHUYENs = new EntitySet<CHITIETCHUYEN>(new Action<CHITIETCHUYEN>(this.attach_CHITIETCHUYENs), new Action<CHITIETCHUYEN>(this.detach_CHITIETCHUYENs));
			this._CHONGOIs = new EntitySet<CHONGOI>(new Action<CHONGOI>(this.attach_CHONGOIs), new Action<CHONGOI>(this.detach_CHONGOIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXE", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAXE
		{
			get
			{
				return this._MAXE;
			}
			set
			{
				if ((this._MAXE != value))
				{
					this.OnMAXEChanging(value);
					this.SendPropertyChanging();
					this._MAXE = value;
					this.SendPropertyChanged("MAXE");
					this.OnMAXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENXE", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TENXE
		{
			get
			{
				return this._TENXE;
			}
			set
			{
				if ((this._TENXE != value))
				{
					this.OnTENXEChanging(value);
					this.SendPropertyChanging();
					this._TENXE = value;
					this.SendPropertyChanged("TENXE");
					this.OnTENXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODT", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string SODT
		{
			get
			{
				return this._SODT;
			}
			set
			{
				if ((this._SODT != value))
				{
					this.OnSODTChanging(value);
					this.SendPropertyChanging();
					this._SODT = value;
					this.SendPropertyChanged("SODT");
					this.OnSODTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCHO", DbType="Int NOT NULL")]
		public int SOCHO
		{
			get
			{
				return this._SOCHO;
			}
			set
			{
				if ((this._SOCHO != value))
				{
					this.OnSOCHOChanging(value);
					this.SendPropertyChanging();
					this._SOCHO = value;
					this.SendPropertyChanged("SOCHO");
					this.OnSOCHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XE_CHITIETCHUYEN", Storage="_CHITIETCHUYENs", ThisKey="MAXE", OtherKey="MAXE")]
		public EntitySet<CHITIETCHUYEN> CHITIETCHUYENs
		{
			get
			{
				return this._CHITIETCHUYENs;
			}
			set
			{
				this._CHITIETCHUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XE_CHONGOI", Storage="_CHONGOIs", ThisKey="MAXE", OtherKey="MAXE")]
		public EntitySet<CHONGOI> CHONGOIs
		{
			get
			{
				return this._CHONGOIs;
			}
			set
			{
				this._CHONGOIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETCHUYENs(CHITIETCHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.XE = this;
		}
		
		private void detach_CHITIETCHUYENs(CHITIETCHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.XE = null;
		}
		
		private void attach_CHONGOIs(CHONGOI entity)
		{
			this.SendPropertyChanging();
			entity.XE = this;
		}
		
		private void detach_CHONGOIs(CHONGOI entity)
		{
			this.SendPropertyChanging();
			entity.XE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHONGOI")]
	public partial class CHONGOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACHONGOI;
		
		private string _VITRI;
		
		private string _MAXE;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private EntityRef<XE> _XE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHONGOIChanging(string value);
    partial void OnMACHONGOIChanged();
    partial void OnVITRIChanging(string value);
    partial void OnVITRIChanged();
    partial void OnMAXEChanging(string value);
    partial void OnMAXEChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public CHONGOI()
		{
			this._XE = default(EntityRef<XE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHONGOI", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACHONGOI
		{
			get
			{
				return this._MACHONGOI;
			}
			set
			{
				if ((this._MACHONGOI != value))
				{
					this.OnMACHONGOIChanging(value);
					this.SendPropertyChanging();
					this._MACHONGOI = value;
					this.SendPropertyChanged("MACHONGOI");
					this.OnMACHONGOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VITRI", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string VITRI
		{
			get
			{
				return this._VITRI;
			}
			set
			{
				if ((this._VITRI != value))
				{
					this.OnVITRIChanging(value);
					this.SendPropertyChanging();
					this._VITRI = value;
					this.SendPropertyChanged("VITRI");
					this.OnVITRIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXE", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MAXE
		{
			get
			{
				return this._MAXE;
			}
			set
			{
				if ((this._MAXE != value))
				{
					if (this._XE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAXEChanging(value);
					this.SendPropertyChanging();
					this._MAXE = value;
					this.SendPropertyChanged("MAXE");
					this.OnMAXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XE_CHONGOI", Storage="_XE", ThisKey="MAXE", OtherKey="MAXE", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public XE XE
		{
			get
			{
				return this._XE.Entity;
			}
			set
			{
				XE previousValue = this._XE.Entity;
				if (((previousValue != value) 
							|| (this._XE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XE.Entity = null;
						previousValue.CHONGOIs.Remove(this);
					}
					this._XE.Entity = value;
					if ((value != null))
					{
						value.CHONGOIs.Add(this);
						this._MAXE = value.MAXE;
					}
					else
					{
						this._MAXE = default(string);
					}
					this.SendPropertyChanged("XE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACH")]
	public partial class KHACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKHACH;
		
		private string _TENKHACH;
		
		private string _SDT;
		
		private string _EMAIL;
		
		private string _DIACHI;
		
		private EntitySet<VE> _VEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHACHChanging(string value);
    partial void OnMAKHACHChanged();
    partial void OnTENKHACHChanging(string value);
    partial void OnTENKHACHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public KHACH()
		{
			this._VEs = new EntitySet<VE>(new Action<VE>(this.attach_VEs), new Action<VE>(this.detach_VEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHACH", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKHACH
		{
			get
			{
				return this._MAKHACH;
			}
			set
			{
				if ((this._MAKHACH != value))
				{
					this.OnMAKHACHChanging(value);
					this.SendPropertyChanging();
					this._MAKHACH = value;
					this.SendPropertyChanged("MAKHACH");
					this.OnMAKHACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHACH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TENKHACH
		{
			get
			{
				return this._TENKHACH;
			}
			set
			{
				if ((this._TENKHACH != value))
				{
					this.OnTENKHACHChanging(value);
					this.SendPropertyChanging();
					this._TENKHACH = value;
					this.SendPropertyChanged("TENKHACH");
					this.OnTENKHACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(200)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_VE", Storage="_VEs", ThisKey="MAKHACH", OtherKey="MAKH")]
		public EntitySet<VE> VEs
		{
			get
			{
				return this._VEs;
			}
			set
			{
				this._VEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.KHACH = this;
		}
		
		private void detach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.KHACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MANHINH")]
	public partial class MANHINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAMH;
		
		private string _TENMH;
		
		private EntitySet<PHANQUYEN> _PHANQUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAMHChanging(string value);
    partial void OnMAMHChanged();
    partial void OnTENMHChanging(string value);
    partial void OnTENMHChanged();
    #endregion
		
		public MANHINH()
		{
			this._PHANQUYENs = new EntitySet<PHANQUYEN>(new Action<PHANQUYEN>(this.attach_PHANQUYENs), new Action<PHANQUYEN>(this.detach_PHANQUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMH", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAMH
		{
			get
			{
				return this._MAMH;
			}
			set
			{
				if ((this._MAMH != value))
				{
					this.OnMAMHChanging(value);
					this.SendPropertyChanging();
					this._MAMH = value;
					this.SendPropertyChanged("MAMH");
					this.OnMAMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENMH
		{
			get
			{
				return this._TENMH;
			}
			set
			{
				if ((this._TENMH != value))
				{
					this.OnTENMHChanging(value);
					this.SendPropertyChanging();
					this._TENMH = value;
					this.SendPropertyChanged("TENMH");
					this.OnTENMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MANHINH_PHANQUYEN", Storage="_PHANQUYENs", ThisKey="MAMH", OtherKey="MAMH")]
		public EntitySet<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this._PHANQUYENs;
			}
			set
			{
				this._PHANQUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.MANHINH = this;
		}
		
		private void detach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.MANHINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NDNHOMND")]
	public partial class NDNHOMND : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TENDN;
		
		private string _MANHOM;
		
		private string _GHICHU;
		
		private EntityRef<NGUOIDUNG> _NGUOIDUNG;
		
		private EntityRef<NHOMNGUOIDUNG> _NHOMNGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnMANHOMChanging(string value);
    partial void OnMANHOMChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public NDNHOMND()
		{
			this._NGUOIDUNG = default(EntityRef<NGUOIDUNG>);
			this._NHOMNGUOIDUNG = default(EntityRef<NHOMNGUOIDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					if (this._NGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOM", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHOM
		{
			get
			{
				return this._MANHOM;
			}
			set
			{
				if ((this._MANHOM != value))
				{
					if (this._NHOMNGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHOMChanging(value);
					this.SendPropertyChanging();
					this._MANHOM = value;
					this.SendPropertyChanged("MANHOM");
					this.OnMANHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(50)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_NDNHOMND", Storage="_NGUOIDUNG", ThisKey="TENDN", OtherKey="TENDN", IsForeignKey=true)]
		public NGUOIDUNG NGUOIDUNG
		{
			get
			{
				return this._NGUOIDUNG.Entity;
			}
			set
			{
				NGUOIDUNG previousValue = this._NGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDUNG.Entity = null;
						previousValue.NDNHOMNDs.Remove(this);
					}
					this._NGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.NDNHOMNDs.Add(this);
						this._TENDN = value.TENDN;
					}
					else
					{
						this._TENDN = default(string);
					}
					this.SendPropertyChanged("NGUOIDUNG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOMNGUOIDUNG_NDNHOMND", Storage="_NHOMNGUOIDUNG", ThisKey="MANHOM", OtherKey="MANHOM", IsForeignKey=true)]
		public NHOMNGUOIDUNG NHOMNGUOIDUNG
		{
			get
			{
				return this._NHOMNGUOIDUNG.Entity;
			}
			set
			{
				NHOMNGUOIDUNG previousValue = this._NHOMNGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NHOMNGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHOMNGUOIDUNG.Entity = null;
						previousValue.NDNHOMNDs.Remove(this);
					}
					this._NHOMNGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.NDNHOMNDs.Add(this);
						this._MANHOM = value.MANHOM;
					}
					else
					{
						this._MANHOM = default(string);
					}
					this.SendPropertyChanged("NHOMNGUOIDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TENDN;
		
		private string _MK;
		
		private System.Nullable<bool> _HOATDONG;
		
		private EntitySet<NDNHOMND> _NDNHOMNDs;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnMKChanging(string value);
    partial void OnMKChanged();
    partial void OnHOATDONGChanging(System.Nullable<bool> value);
    partial void OnHOATDONGChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			this._NDNHOMNDs = new EntitySet<NDNHOMND>(new Action<NDNHOMND>(this.attach_NDNHOMNDs), new Action<NDNHOMND>(this.detach_NDNHOMNDs));
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MK", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MK
		{
			get
			{
				return this._MK;
			}
			set
			{
				if ((this._MK != value))
				{
					this.OnMKChanging(value);
					this.SendPropertyChanging();
					this._MK = value;
					this.SendPropertyChanged("MK");
					this.OnMKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOATDONG", DbType="Bit")]
		public System.Nullable<bool> HOATDONG
		{
			get
			{
				return this._HOATDONG;
			}
			set
			{
				if ((this._HOATDONG != value))
				{
					this.OnHOATDONGChanging(value);
					this.SendPropertyChanging();
					this._HOATDONG = value;
					this.SendPropertyChanged("HOATDONG");
					this.OnHOATDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_NDNHOMND", Storage="_NDNHOMNDs", ThisKey="TENDN", OtherKey="TENDN")]
		public EntitySet<NDNHOMND> NDNHOMNDs
		{
			get
			{
				return this._NDNHOMNDs;
			}
			set
			{
				this._NDNHOMNDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_NGUOIDUNG", Storage="_NHANVIEN", ThisKey="TENDN", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.NGUOIDUNG = null;
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.NGUOIDUNG = this;
						this._TENDN = value.MANV;
					}
					else
					{
						this._TENDN = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NDNHOMNDs(NDNHOMND entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = this;
		}
		
		private void detach_NDNHOMNDs(NDNHOMND entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _TENNV;
		
		private string _SDT;
		
		private string _EMAIL;
		
		private string _DIACHI;
		
		private EntityRef<NGUOIDUNG> _NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._NGUOIDUNG = default(EntityRef<NGUOIDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(200)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_NGUOIDUNG", Storage="_NGUOIDUNG", ThisKey="MANV", OtherKey="TENDN", IsUnique=true, IsForeignKey=false)]
		public NGUOIDUNG NGUOIDUNG
		{
			get
			{
				return this._NGUOIDUNG.Entity;
			}
			set
			{
				NGUOIDUNG previousValue = this._NGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDUNG.Entity = null;
						previousValue.NHANVIEN = null;
					}
					this._NGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.NHANVIEN = this;
					}
					this.SendPropertyChanged("NGUOIDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHOMNGUOIDUNG")]
	public partial class NHOMNGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHOM;
		
		private string _TENNHOMND;
		
		private string _GHICHU;
		
		private EntitySet<NDNHOMND> _NDNHOMNDs;
		
		private EntitySet<PHANQUYEN> _PHANQUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHOMChanging(string value);
    partial void OnMANHOMChanged();
    partial void OnTENNHOMNDChanging(string value);
    partial void OnTENNHOMNDChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public NHOMNGUOIDUNG()
		{
			this._NDNHOMNDs = new EntitySet<NDNHOMND>(new Action<NDNHOMND>(this.attach_NDNHOMNDs), new Action<NDNHOMND>(this.detach_NDNHOMNDs));
			this._PHANQUYENs = new EntitySet<PHANQUYEN>(new Action<PHANQUYEN>(this.attach_PHANQUYENs), new Action<PHANQUYEN>(this.detach_PHANQUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOM", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHOM
		{
			get
			{
				return this._MANHOM;
			}
			set
			{
				if ((this._MANHOM != value))
				{
					this.OnMANHOMChanging(value);
					this.SendPropertyChanging();
					this._MANHOM = value;
					this.SendPropertyChanged("MANHOM");
					this.OnMANHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNHOMND", DbType="NVarChar(50)")]
		public string TENNHOMND
		{
			get
			{
				return this._TENNHOMND;
			}
			set
			{
				if ((this._TENNHOMND != value))
				{
					this.OnTENNHOMNDChanging(value);
					this.SendPropertyChanging();
					this._TENNHOMND = value;
					this.SendPropertyChanged("TENNHOMND");
					this.OnTENNHOMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(50)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOMNGUOIDUNG_NDNHOMND", Storage="_NDNHOMNDs", ThisKey="MANHOM", OtherKey="MANHOM")]
		public EntitySet<NDNHOMND> NDNHOMNDs
		{
			get
			{
				return this._NDNHOMNDs;
			}
			set
			{
				this._NDNHOMNDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOMNGUOIDUNG_PHANQUYEN", Storage="_PHANQUYENs", ThisKey="MANHOM", OtherKey="MANHOM")]
		public EntitySet<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this._PHANQUYENs;
			}
			set
			{
				this._PHANQUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NDNHOMNDs(NDNHOMND entity)
		{
			this.SendPropertyChanging();
			entity.NHOMNGUOIDUNG = this;
		}
		
		private void detach_NDNHOMNDs(NDNHOMND entity)
		{
			this.SendPropertyChanging();
			entity.NHOMNGUOIDUNG = null;
		}
		
		private void attach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.NHOMNGUOIDUNG = this;
		}
		
		private void detach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.NHOMNGUOIDUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANQUYEN")]
	public partial class PHANQUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHOM;
		
		private string _MAMH;
		
		private string _QUYEN;
		
		private EntityRef<MANHINH> _MANHINH;
		
		private EntityRef<NHOMNGUOIDUNG> _NHOMNGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHOMChanging(string value);
    partial void OnMANHOMChanged();
    partial void OnMAMHChanging(string value);
    partial void OnMAMHChanged();
    partial void OnQUYENChanging(string value);
    partial void OnQUYENChanged();
    #endregion
		
		public PHANQUYEN()
		{
			this._MANHINH = default(EntityRef<MANHINH>);
			this._NHOMNGUOIDUNG = default(EntityRef<NHOMNGUOIDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOM", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHOM
		{
			get
			{
				return this._MANHOM;
			}
			set
			{
				if ((this._MANHOM != value))
				{
					if (this._NHOMNGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHOMChanging(value);
					this.SendPropertyChanging();
					this._MANHOM = value;
					this.SendPropertyChanged("MANHOM");
					this.OnMANHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMH", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAMH
		{
			get
			{
				return this._MAMH;
			}
			set
			{
				if ((this._MAMH != value))
				{
					if (this._MANHINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAMHChanging(value);
					this.SendPropertyChanging();
					this._MAMH = value;
					this.SendPropertyChanged("MAMH");
					this.OnMAMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYEN", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string QUYEN
		{
			get
			{
				return this._QUYEN;
			}
			set
			{
				if ((this._QUYEN != value))
				{
					this.OnQUYENChanging(value);
					this.SendPropertyChanging();
					this._QUYEN = value;
					this.SendPropertyChanged("QUYEN");
					this.OnQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MANHINH_PHANQUYEN", Storage="_MANHINH", ThisKey="MAMH", OtherKey="MAMH", IsForeignKey=true)]
		public MANHINH MANHINH
		{
			get
			{
				return this._MANHINH.Entity;
			}
			set
			{
				MANHINH previousValue = this._MANHINH.Entity;
				if (((previousValue != value) 
							|| (this._MANHINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MANHINH.Entity = null;
						previousValue.PHANQUYENs.Remove(this);
					}
					this._MANHINH.Entity = value;
					if ((value != null))
					{
						value.PHANQUYENs.Add(this);
						this._MAMH = value.MAMH;
					}
					else
					{
						this._MAMH = default(string);
					}
					this.SendPropertyChanged("MANHINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOMNGUOIDUNG_PHANQUYEN", Storage="_NHOMNGUOIDUNG", ThisKey="MANHOM", OtherKey="MANHOM", IsForeignKey=true)]
		public NHOMNGUOIDUNG NHOMNGUOIDUNG
		{
			get
			{
				return this._NHOMNGUOIDUNG.Entity;
			}
			set
			{
				NHOMNGUOIDUNG previousValue = this._NHOMNGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NHOMNGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHOMNGUOIDUNG.Entity = null;
						previousValue.PHANQUYENs.Remove(this);
					}
					this._NHOMNGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.PHANQUYENs.Add(this);
						this._MANHOM = value.MANHOM;
					}
					else
					{
						this._MANHOM = default(string);
					}
					this.SendPropertyChanged("NHOMNGUOIDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIXE")]
	public partial class TAIXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATAIXE;
		
		private string _TENTAIXE;
		
		private string _SDT;
		
		private string _SOGPLX;
		
		private EntitySet<CHITIETCHUYEN> _CHITIETCHUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATAIXEChanging(string value);
    partial void OnMATAIXEChanged();
    partial void OnTENTAIXEChanging(string value);
    partial void OnTENTAIXEChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnSOGPLXChanging(string value);
    partial void OnSOGPLXChanged();
    #endregion
		
		public TAIXE()
		{
			this._CHITIETCHUYENs = new EntitySet<CHITIETCHUYEN>(new Action<CHITIETCHUYEN>(this.attach_CHITIETCHUYENs), new Action<CHITIETCHUYEN>(this.detach_CHITIETCHUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATAIXE", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATAIXE
		{
			get
			{
				return this._MATAIXE;
			}
			set
			{
				if ((this._MATAIXE != value))
				{
					this.OnMATAIXEChanging(value);
					this.SendPropertyChanging();
					this._MATAIXE = value;
					this.SendPropertyChanged("MATAIXE");
					this.OnMATAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTAIXE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TENTAIXE
		{
			get
			{
				return this._TENTAIXE;
			}
			set
			{
				if ((this._TENTAIXE != value))
				{
					this.OnTENTAIXEChanging(value);
					this.SendPropertyChanging();
					this._TENTAIXE = value;
					this.SendPropertyChanged("TENTAIXE");
					this.OnTENTAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOGPLX", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SOGPLX
		{
			get
			{
				return this._SOGPLX;
			}
			set
			{
				if ((this._SOGPLX != value))
				{
					this.OnSOGPLXChanging(value);
					this.SendPropertyChanging();
					this._SOGPLX = value;
					this.SendPropertyChanged("SOGPLX");
					this.OnSOGPLXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIXE_CHITIETCHUYEN", Storage="_CHITIETCHUYENs", ThisKey="MATAIXE", OtherKey="MATAIXE")]
		public EntitySet<CHITIETCHUYEN> CHITIETCHUYENs
		{
			get
			{
				return this._CHITIETCHUYENs;
			}
			set
			{
				this._CHITIETCHUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETCHUYENs(CHITIETCHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIXE = this;
		}
		
		private void detach_CHITIETCHUYENs(CHITIETCHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIXE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUYEN")]
	public partial class TUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATUYEN;
		
		private string _DIEMDI;
		
		private string _DIEMDEN;
		
		private EntitySet<CHITIETCHUYEN> _CHITIETCHUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATUYENChanging(string value);
    partial void OnMATUYENChanged();
    partial void OnDIEMDIChanging(string value);
    partial void OnDIEMDIChanged();
    partial void OnDIEMDENChanging(string value);
    partial void OnDIEMDENChanged();
    #endregion
		
		public TUYEN()
		{
			this._CHITIETCHUYENs = new EntitySet<CHITIETCHUYEN>(new Action<CHITIETCHUYEN>(this.attach_CHITIETCHUYENs), new Action<CHITIETCHUYEN>(this.detach_CHITIETCHUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATUYEN", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATUYEN
		{
			get
			{
				return this._MATUYEN;
			}
			set
			{
				if ((this._MATUYEN != value))
				{
					this.OnMATUYENChanging(value);
					this.SendPropertyChanging();
					this._MATUYEN = value;
					this.SendPropertyChanged("MATUYEN");
					this.OnMATUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMDI", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIEMDI
		{
			get
			{
				return this._DIEMDI;
			}
			set
			{
				if ((this._DIEMDI != value))
				{
					this.OnDIEMDIChanging(value);
					this.SendPropertyChanging();
					this._DIEMDI = value;
					this.SendPropertyChanged("DIEMDI");
					this.OnDIEMDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMDEN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIEMDEN
		{
			get
			{
				return this._DIEMDEN;
			}
			set
			{
				if ((this._DIEMDEN != value))
				{
					this.OnDIEMDENChanging(value);
					this.SendPropertyChanging();
					this._DIEMDEN = value;
					this.SendPropertyChanged("DIEMDEN");
					this.OnDIEMDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUYEN_CHITIETCHUYEN", Storage="_CHITIETCHUYENs", ThisKey="MATUYEN", OtherKey="MATUYEN")]
		public EntitySet<CHITIETCHUYEN> CHITIETCHUYENs
		{
			get
			{
				return this._CHITIETCHUYENs;
			}
			set
			{
				this._CHITIETCHUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETCHUYENs(CHITIETCHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TUYEN = this;
		}
		
		private void detach_CHITIETCHUYENs(CHITIETCHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VE")]
	public partial class VE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAVE;
		
		private string _MACHUYEN;
		
		private string _MAKH;
		
		private string _MANV;
		
		private System.DateTime _NGAYTAO;
		
		private string _CHONGOI;
		
		private string _TRANGTHAI;
		
		private EntityRef<KHACH> _KHACH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAVEChanging(string value);
    partial void OnMAVEChanged();
    partial void OnMACHUYENChanging(string value);
    partial void OnMACHUYENChanged();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnNGAYTAOChanging(System.DateTime value);
    partial void OnNGAYTAOChanged();
    partial void OnCHONGOIChanging(string value);
    partial void OnCHONGOIChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public VE()
		{
			this._KHACH = default(EntityRef<KHACH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAVE", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAVE
		{
			get
			{
				return this._MAVE;
			}
			set
			{
				if ((this._MAVE != value))
				{
					this.OnMAVEChanging(value);
					this.SendPropertyChanging();
					this._MAVE = value;
					this.SendPropertyChanged("MAVE");
					this.OnMAVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUYEN", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MACHUYEN
		{
			get
			{
				return this._MACHUYEN;
			}
			set
			{
				if ((this._MACHUYEN != value))
				{
					this.OnMACHUYENChanging(value);
					this.SendPropertyChanging();
					this._MACHUYEN = value;
					this.SendPropertyChanged("MACHUYEN");
					this.OnMACHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAO", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYTAO
		{
			get
			{
				return this._NGAYTAO;
			}
			set
			{
				if ((this._NGAYTAO != value))
				{
					this.OnNGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAO = value;
					this.SendPropertyChanged("NGAYTAO");
					this.OnNGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHONGOI", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string CHONGOI
		{
			get
			{
				return this._CHONGOI;
			}
			set
			{
				if ((this._CHONGOI != value))
				{
					this.OnCHONGOIChanging(value);
					this.SendPropertyChanging();
					this._CHONGOI = value;
					this.SendPropertyChanged("CHONGOI");
					this.OnCHONGOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="NVarChar(100)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_VE", Storage="_KHACH", ThisKey="MAKH", OtherKey="MAKHACH", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public KHACH KHACH
		{
			get
			{
				return this._KHACH.Entity;
			}
			set
			{
				KHACH previousValue = this._KHACH.Entity;
				if (((previousValue != value) 
							|| (this._KHACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH.Entity = null;
						previousValue.VEs.Remove(this);
					}
					this._KHACH.Entity = value;
					if ((value != null))
					{
						value.VEs.Add(this);
						this._MAKH = value.MAKHACH;
					}
					else
					{
						this._MAKH = default(string);
					}
					this.SendPropertyChanged("KHACH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
